language: generic
sudo: required
services:
  - docker  

before_install:
  - docker build -t hsefati/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hsefati/react-test npm run test

after_success:
  - doccker build -t hsefati/multi-client ./client
  - doccker build -t hsefati/multi-nginx ./nginx
  - doccker build -t hsefati/multi-server ./server
  - doccker build -t hsefati/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # tkae those images and push them to docker hub
  - docker push hsefati/multi-client
  - docker push hsefati/multi-nginx
  - docker push hsefati/multi-server
  - docker push hsefati/multi-worker
