sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hsefati/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hsefati/react-test npm test

after_success:
  - docker build -t hsefati/multi-client ./client
  - docker build -t hsefati/multi-nginx ./nginx
  - docker build -t hsefati/multi-server ./server
  - docker build -t hsefati/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push hsefati/multi-client
  - docker push hsefati/multi-nginx
  - docker push hsefati/multi-server
  - docker push hsefati/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-0596894859455"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
